server:
  port: 8050
  servlet:
    context-path: /dataadapter   
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 12345678
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  datasource:
        name: test  
        url: jdbc:mysql://localhost:3306/jnretail8888_2?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 5
        maxWait: 60000
        minIdle: 10
        timeBetweenEvictionRunsMillis: 2000
        minEvictableIdleTimeMillis: 600000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath:/cn/jiafeng/erp/data/adapter/dao/mapper/*.xml
  typeAliasesPackage: cn.jiafeng.erp.data.adapter.dao.entity
logging:
  config: classpath:log4j2.yml
  level:
    cn.jiafeng.erp.data.adapter.dao: debug